[build]
  command = "npm run build"
  publish = ".vinxi/build/client/_build"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "20"

[[edge_functions]]
  function = "server"
  path = "/*"
